title: BARS BENCHMARK
author: RECZOO Community
copyright: 2020-2024
logo: ""
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output: show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: BARS.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ./CTR/references.bib
  - ./Matching/references.bib

parse:
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Information about where the book exists on the web
repository:
  url: https://github.com/reczoo/BARS # Online location of your book
  # path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_navbar: '<img src="https://openbenchmark.github.io/BARS/_images/wechat.jpg" title="QR Code"><br>Join Wechat Group</br>' # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.

sphinx:
  config:
    bibtex_reference_style: label
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # html_js_files:
    # - https://cdn.datatables.net/r/zf-5.5.2/jqc-1.11.3,dt-1.10.8/datatables.min.js
    # - https://code.highcharts.com/highcharts.js
    # - https://code.highcharts.com/modules/no-data-to-display.js
    # # - https://openbenchmark.github.io/BarsCTR/js/tablecharts.js
    # html_css_files:
    # # - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
    # - https://cdn.datatables.net/r/zf-5.5.2/jqc-1.11.3,dt-1.10.8/datatables.min.css
